# Site settings
title: Arpit Soni
email: email@iarpits.com
url: https://iarpits.com
description: "I am a Software Engineer. This is my my personal site where you can find my resume, blogs and social handles."
keywords: "iarpits, blog, portfolio, resume, arpit, soni, ios, swift"
skills: "Swift - Dart - JavaScript - C++ - Python - Kotlin - Flutter - Vue.js - Azure - Firebase"
qoute: "I love challenging problems, I don't worry about the How?"
meta_author: Arpit Soni

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Arpit Soni
  location: Location
  social: Around the Web
  contact: Contact
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/iarpits
  # - title: facebook
  #   url:
  - title: stack-overflow
    url: https://stackoverflow.com/users/7254526/iaarpit
  # - title: bitbucket
  #   url:
  - title: github
    url: https://github.com/iarpits
  - title: medium
    url: https://medium.com/@iarpits

# Postal address (add as many lines as necessary)
address:
  - line: Washington D.C. Metro Area

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: none

# theme: jekyll-theme-cayman

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag